# Generated by Django 2.2.5 on 2020-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Date', models.DateField(auto_now=True)),
                ('Description', models.CharField(max_length=100)),
                ('Entry', models.CharField(max_length=500)),
            ],
        ),
    ]
