# Generated by Django 2.2.5 on 2020-04-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Projected', models.BigIntegerField()),
                ('Actual', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HiddenStatus_Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
