# Generated by Django 2.2.5 on 2020-04-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200407_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='Username',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
